### ISSUE TITLE
Buttons too close to Tabs

### ISSUE THREAD

**Issue by itaie01** [fellowish/firefox-review#10]
Just wanted to say that I love the theme, it really plays to firefox's strengths and makes it feel unique in terms of browser design language.

My one issue with it is a UI issue where the Buttons on Mac interfere with the tabs as seen as the picture below.

<img width="342" alt="image" src="https://user-images.githubusercontent.com/44759817/84704005-2191a580-af27-11ea-9e81-baff065dd0a0.png">

**Comment by fellowish** [comment]
Mac support will be coming eventually. Most likely with 1.3.
