### ISSUE TITLE
[Bug] v1.1.2 is completely broken in beta version 78

### ISSUE THREAD

**Issue by adsamcik** [fellowish/firefox-review#13]
I double checked everything and it seemed to be setup correctly, 1.1.1 works just fine but with 1.1.2 tabs have no background, menu has no background, it is completely unusable.

**Comment by fellowish** [comment]
Welp, there goes my weekend. Thanks for the heads up.

**Comment by adsamcik** [comment]
ok this is weird, I tried it out in dev edition and there it works fine

**Comment by fellowish** [comment]
Was about to say the same thing. You're talking about a Nightly Build? And if so, specify the version?

**Comment by adsamcik** [comment]
not nightly, beta. It is possible that it was some firefox issue specific to that build I had, cause I tried it again now and it's fine even in beta. In the meantime my ff got updated so it's definitely possible it was just issue with that specific build or something like that.

It seems unlikely to me, that I would make a mistake in copying the css files 3-4 times before tbh.
