### ISSUE TITLE
[Bug] (1.1.2) Firefox's Default theme doesn't inherit any colors

### ISSUE THREAD

**Issue by matfantinel** [fellowish/firefox-review#14]
**Describe the bug**
I have updated to 1.1.2, and used to have the Adaptive theme. Now on 1.1.2, colors only apply if I apply Light/Dark theme manually on Firefox's customization menu. If I leave "Default", the URL bar becomes transparent. I'd like to get the auto-switching back, because I change between Light/Dark themes in my OS multiple times a day.

**To Reproduce**
1. Apply 1.1.2 version of this theme
2. Go to Firefox's "Customize" menu
3. Select "Default" theme, that should automatically change between light/dark according to OS preference
4. Theme colors don't get applied.

**Screenshots**
![image](https://user-images.githubusercontent.com/24247035/85599821-453da580-b623-11ea-9b31-9afdb4a8195a.png)

**Diagnostics:**
 - OS: Pop!_OS 20.04
 - Firefox Version 77.0.1
 - Firefox Review Version v1.1.2

**Comment by fellowish** [comment]
Less of a bug, more of a request. But nevertheless, it's very much an interesting one, and feasible as well. 

I'll see what I can do.

**Comment by matfantinel** [comment]
Hah, I figured it was a bug because it was working before. Guess it was an accidental feature on 1.1.1? hahah

**Comment by fellowish** [comment]
I changed the adaptive theming to theming based on the customization menu. But I can think of a way to have the "default" theme in the customization menu change Review's colors depending on the OS's theme, so we can have both at the same time.

**Comment by fellowish** [comment]
Feature added in v1.1.3!
