### ISSUE TITLE
URL bar not themed on Firefox 77

### ISSUE THREAD

**Issue by Virkkunen** [fellowish/firefox-review#6]
Using Firefox 77 on Windows, it seems that the URL bar is not themed. It also makes the text really hard to read.
  
![](https://files.catbox.moe/yvrs6q.png)
  
It also seems that Mozilla removed the flag to revert to the old URL bar.

**Comment by fellowish** [comment]
Fixed in v1.1.1. urlBar element was reformatted for some reason. Had to target it a different way than normal. Thanks for the bug report!
