### ISSUE TITLE
Megabar on Firefox 77+

### ISSUE THREAD

**Issue by ghost** [fellowish/firefox-review#8]
Since they removed the about:config way to remove mega bar, is it possible to add it to firefox review. 

any updates on other things coming? like the library window

**Comment by fellowish** [comment]
Currently I am caught up in the middle of... Well, everything that's happening around the U.S. currently. This significantly delayed my plans on updating. 

I was working on library/protection menus for the next update, as well as some bugs with the download and library buttons. I can try to see what I can do with the megabar itself, though!

**Comment by ghost** [comment]
Thanks no worries take your time
