### ISSUE TITLE
Black background on uBlock element picker

### ISSUE THREAD

**Issue by Virkkunen** [fellowish/firefox-review#9]
I've noticed that whenever I enter uBlock Origin's element picker, the background goes completely dark, making it impossible to see what I'm picking. The expected behavior is that the background goes darker but is still visible. 
  
Issue only happes with Firefox Review so far.

![](https://i.imgur.com/tRluLYA.png)

**Comment by fellowish** [comment]
It's probably been fixed with v1.1.2, although there might still be some troubles here. userContent was targetting the html of uBlock's element picker. Let me know if there is still an issue.

**Comment by Virkkunen** [comment]
Managed to update the style and so far so good!
 ![](https://files.catbox.moe/nkvlya.png)
  
Issue seems to be solved, and thanks for the work!
